name: RllibAgent
weights: configs/rllib-agent.pt
framework: torch
model:
  custom_model: nature_cnn_rnn
  custom_model_config:
    cnn_shape_chw:
    - 2
    - 192
    - 256
    fields:
    - grayscale
    - depth
    hidden_size: 128
    rnn_type: LSTM
