# logging
log_root: ray_results/challenge
experiment_name: baseline

# gym environment
env_config:
  # fields given to policy for training
  fields:
  - depth
  - grayscale
  camWidth: 256
  camHeight: 192
  max_steps: 200  # needs to be less than sgd_minibatch_size

# ray evaluation 
evaluation_config:
  record_env: true
  render_env: true
evaluation_interval: 0  # Set this to a positive integer to enable evaluations during training
evaluation_duration: 50
evaluation_num_workers: 0

# training 
framework: torch
log_level: "INFO"
train_batch_size: 1024
lr: 0.0001

# ppo specific 
lambda: 0.9
sgd_minibatch_size: 256
vf_clip_param: 50
vf_loss_coeff: 0.25
clip_param: 0.2
entropy_coeff: 0.0


# custom model with rnn
model:
  custom_model: nature_cnn_rnn
  custom_model_config:
    cnn_shape_chw:
    - 2
    - 192
    - 256
    fields:
    - depth
    - grayscale
    hidden_size: 128
    rnn_type: LSTM

# custom model without rnn
# model:
#   custom_model: nature_cnn
#   custom_model_config:
#     cnn_shape_chw:
#     - 2
#     - 192
#     - 256
#     fields:
#     - depth
#     - grayscale

# built in model (with lstm)
# model:
#   fcnet_hiddens: [512, 256]
#   fcnet_activation: "tanh"
#   use_lstm: True

# training environment
num_envs_per_worker: 1
num_gpus: 1
num_sgd_iter: 8
num_workers: 0
num_training_iterations: 1000
checkpoint_save_frequency: 100