# logging
log_root: ray_results/challenge
experiment_name: baseline

# gym environment
env_config:
  # fields given to policy for training
  fields:
  - depth
  - image
  resolution: minimal

# ray evaluation 
evaluation_config:
  record_env: true
  render_env: true
evaluation_interval: 0  # Set this to a positive integer to enable evaluations during training
evaluation_num_episodes: 50
evaluation_num_workers: 0

# ppo 
framework: torch
gamma: 0.999
horizon: null
lambda: 0.9
log_level: DEBUG 
lr: 0.0001
sgd_minibatch_size: 128
train_batch_size: 512
vf_clip_param: 50
vf_loss_coeff: 0.25
vf_share_layers: false
clip_param: 0.2
entropy_coeff: 0.01


# model 
model:
  custom_model: nature_cnn_rnn
  custom_model_config:
    cnn_shape_chw:
    - 4
    - 192
    - 256
    fields:
    - image
    - depth
    hidden_size: 256
    rnn_type: LSTM
  max_seq_len: 300

# training environment
num_envs_per_worker: 1
num_gpus: 1
num_sgd_iter: 8
num_workers: 1
num_training_iterations: 1000
checkpoint_save_frequency: 100